### PR TITLE
added GENious to risset

### PR DESCRIPTION
**Pull request by PvonN**
Added my plugin repo "GENious" to Risset. Holds by now a GEN routine based on the lorenz attractor. Other will follow soon.

### CODE REVIEW

**Comment by PvonN** [comment]
Can we merge this or is there a problem with my pull request in any form?

**Comment by gesellkammer** [comment]
Thanks for contributing. Some remarks before this entry can be added.

The risset.json file in your repo does not conform to the expected schema. 

```bash
» risset validate risset.json
** Error: Command validate failed
** Error: Error in risset.json: Expected a value of type <class 'list'>, got {'macos': {'url': 'https://github.com/alice/myplugin/releases/genious.zip', 'extractpath': 'genious.dylib', 'build_platform': '13.6.7'}}
```

Look at an example here: https://github.com/csound-plugins/csound-plugins/blob/master/src/poly/risset.json

The linked URL for the one binary is also not valid.

**Comment by PvonN** [comment]
Thanks for advice! solved this now.

**Comment by gesellkammer** [comment]
Your risset.json is still invalid:

```
risset validate risset.json
** Error: Command validate failed
** Error: validate: Error decoding json file 'risset.json': Expecting ',' delimiter: line 4 column 5 (char 52)
```

**Comment by gesellkammer** [comment]
Also it would be great if you can provide binaries for at least all three desktop platforms, the code does not seem to have any dependencies so it might be a matter of making a build script for github actions. For inspiration you can take a look at https://github.com/csound-plugins/csound-plugins/blob/master/.github/workflows/build.yml

**Comment by PvonN** [comment]
Sorry! Checked the risset.json again and added two ','. It must work now.

I never worked with github actions but will look into this to provide binaries for linux and windows!

**Pull request merged**
